// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels():Promise<Array<string>>;

export function SwitchModel(arg1:string):Promise<string>;

export function Translate(arg1:string):Promise<string>;
