// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}
